#%RAML 1.0 DataType
type: object
properties:  
  id:
    type: integer
    required: true
  object_keys:
    type: object
    properties:
      OriginalAssetURL:
        type: string | nil
      ThumbnailURL:
        type: string | nil
      Thumbnail1URL:
        type: string | nil
      BigThumbnailURL:
        type: string | nil
      PreviewURL:
        type: string | nil
      Desktop1URL:
        type: string | nil
      Desktop2URL:
        type: string | nil
      Mobile1URL:
        type: string | nil
      Mobile2URL:
        type: string | nil
      PSDHighResURL:
        type: string | nil
      PSDLowResURL:
        type: string | nil

  
