#%RAML 1.0 NamedExample
  errorMessage: "Unable to delete expired assets from S3 Bucket API: S3::DeleteExpiredAssets."
  errorType: Asset Deletion from S3 Failure.
  correlationId: 65189d64-019c-11eb-adc1-0242ac120002
  errorCode: 548