#%RAML 1.0 NamedExample
  errorMessage: Asset Push to AEM Failure.
  errorType: Unable to invoke AEM::AEMAssetPush API to sync assets from DCH
  correlationId: 65189d64-019c-11eb-adc1-0242ac120002
  errorCode: 545